---
- hosts: ceph-cluster
  become: true
  become_user: "maniaa"
  tasks:
  - name: make direcotry
    file:
      path: "/home/maniaa/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/maniaa/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/maniaa/.ssh/authorized_keys"
      line: "{{ pubkey }}"
